title: Zendesk Garden Jekyll Theme
remote_theme: Fede-Rausa/zendesk_clone0/jekyll-theme-zendesk-garden@main

baseurl: /zendesk_clone0

search_enabled: true
auto_page_title: true

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
