title: Zendesk Garden Jekyll Theme

#I have replaced zendesk with Fede-Rausa (username)
#and jekyll-theme-zendesk-garden with zendesk_clone0 (repository name)
remote_theme: Fede-Rausa/zendesk_clone0@main
baseurl: /zendesk_clone0

search_enabled: true
auto_page_title: true

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
